site_name: Impiger Auth Service

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md

plugins:
  - techdocs-core

# Add this to bypass the strict exit code 1 crash
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: warn
    unrecognized_links: warn
